### ISSUE TITLE
Lists

### ISSUE THREAD

**Issue by NicolasSiver** [NicolasSiver/nodebb-plugin-ns-spoiler#1]
If spoiler is used with lists, without additional space, it creates broken layout.

**Comment by metahusk** [comment]
I can confirm this bug. What do you mean by "without additional space"?

Thanks for the plugin!

**Comment by NicolasSiver** [comment]
Empty line between code and content:

Good:

```
:::

something

:::
```

Could have problems:

```
:::
something is here
:::
```
