### ISSUE TITLE
Spoilers not opening when used with 1.12.1

### ISSUE THREAD

**Issue by saesrpg** [NicolasSiver/nodebb-plugin-ns-spoiler#18]
As per the title.

Not sure if it's just isolated to me, mind looking into it, please?

**Comment by saesrpg** [comment]
Just to add, it seems to work when you create them, but they don't work when you go and visit the post / topic afterwards.

**Comment by NicolasSiver** [comment]
@saesrpg compatibility issue should be resolved in the next major update - v7
