### ISSUE TITLE
Spoiler issue

### ISSUE THREAD

**Issue by Howlze** [NicolasSiver/nodebb-plugin-ns-spoiler#23]
See photo: https://i.imgur.com/lgXGjl2.png

This has happened twice now. As you can see in the second spoiler, instead of the attached images showing, the text repeats itself. The images in the 3rd spoiler aren't the ones actually inserted; this is probably due to spoiler 2 bugging out.

You can see more here: https://saesrpg.uk/post/159291

**Comment by NicolasSiver** [comment]
Hello,

What is the spoiler code? It's important to have extra lines around the spoiler code.

**Comment by Howlze** [comment]
Hello @NicolasSiver,

Here's the entire post including the spoiler codes: https://pastebin.com/raw/aaKEcnM8

Let me know if you need anything else.

**Comment by NicolasSiver** [comment]
Change it to have extra lines between the code symbols:

```
:::

something

:::
```

**Comment by Howlze** [comment]
Thanks @NicolasSiver, that solved the issue.

I'll close this issue.
