### ISSUE TITLE
Support for NodeBB 1.13.x / 1.14.x ?

### ISSUE THREAD

**Issue by Brutus5000** [NicolasSiver/nodebb-plugin-ns-spoiler#25]
Hi there,

I am running a NodeBB on 1.13.3. When installing your plugin the plugin finder only gives me version 4.1.0, which does not work. I assume the latest doesn't show up due to package.json compatibility being `~1.12.0` (and that older version maybe didn't have the correct compatibility settings).

If this plugin is compatible with 1.13.x and/or 1.14.x I'd love to see an update in the package.json and a new npm release :heart: 

Thanks a lot in advance.

**Comment by NicolasSiver** [comment]
if you can help with testing for 1.14/1.15 I can update compatibility requirements.
You can enforce and install the plugin with any version of NodeBB (be careful) via `npm install nodebb-plugin-ns-spoiler`
If you can QA it with a particular NodeBB version (ideally latest) with various types of content - Images, Videos, simple text, multiline text, a mix of those, etc. it will speed up the process greatly.

**Comment by Brutus5000** [comment]
Cool, I will test with the 1.14.2 and 1.14.3 (can't test 1.13 anymore as we already upgraded).
From my understanding your plugin just changes the "view" and doesn't touch the underlying text, so there is no data loss risk, right?

**Comment by NicolasSiver** [comment]
There is no data loss risk, but there is a risk with how content rendered starting with a disability to get spoiler content and ending with an incorrectly rendered topic view. If the plugin is way off, you will not be able to start the forum, for example, because it tries to use some deprecated filter or hook

**Comment by Brutus5000** [comment]
Ok so I installed and activated the plugins version 7.2.0 on NodeBB 1.14.2. The spoiler seems not to work (example [here](https://forum.test.faforever.com/topic/4/hello-stonehenge) in second post). Is there any other information I could provide?

**Comment by Brutus5000** [comment]
Now also tested with NodeBB 1.14.3, still all fine.

**Comment by NicolasSiver** [comment]
When I click your example with Spoiler, it's empty content. What content did you put in the spoiler?

![image](https://user-images.githubusercontent.com/135263/92661871-8e6ccf80-f2cb-11ea-9024-bace2f6cd210.png)

**Comment by Brutus5000** [comment]
Hu weird. I just put the text spoiler in there:
```
:::

spoiler

:::
```
![image](https://user-images.githubusercontent.com/6843462/92699556-067bd980-f34e-11ea-8f4b-85378d87d897.png)

**Comment by Brutus5000** [comment]
Ok this is super weird in an incognito tab it's not working for me as well.

**Comment by SandroJijavadze** [comment]
1.14.3
Once you add the post you need to refresh the page in order for click to show contents.
Might be something related to event delegation, will try to look into it once I have time.

**Comment by NicolasSiver** [comment]
There is a new version of the plugin - v8. It's compatible with NodeBB v1.18
