### ISSUE TITLE
Can't get spoiler content in production env

### ISSUE THREAD

**Issue by wsyscz2** [NicolasSiver/nodebb-plugin-ns-spoiler#7]
https://github.com/NicolasSiver/nodebb-plugin-ns-spoiler/blob/master/plugin/controller.js
line 17-18

``` javascript
// Trigger parsing process, it will invoke `Controller.parsePost` through hooks
async.apply(nodebb.posts.parsePost),
```

this would not trigger parsing process when `global.env === 'production'`, because cache was used in https://github.com/NodeBB/NodeBB/blob/45e412ed7c0a876da177a491c1f03f4623349936/src/posts/parse.js line18-21

``` javascript
if (postData.pid && cache.has(String(postData.pid))) {
	postData.content = cache.get(String(postData.pid));
	return callback(null, postData);
}
```

so you would never get the spoiler content.

**Comment by NicolasSiver** [comment]
Interesting. Content will be received, but it will be an HTML ( a  result of the parse from the previous time).
But because It's not raw data, spoiler content parsing will not provide good results.
